# Reminder: Due to the way GitHub Actions treats reusable workflows that use reusable actions from local paths,
# we have to update .github/workflows/render.yml to point to a particular commit of this file.
# This means that when updating this file, we have to first send a PR that updates the action,
# then second send a PR send that uses the action in the reusable workflow.

name: 'Render'
description: 'Render an OCP Markdown document'
inputs:
  input-md:
    description: 'The name of the Markdown file to render'
    required: true
  output-basename:
    description: 'The base name (without extension) to use for output file(s)'
    required: true
  pdf:
    description: 'Render to PDF'
    required: false
    type: 'boolean'
    default: 'false'
  html:
    description: 'Render to HTML'
    required: false
    type: 'boolean'
    default: 'false'
runs:
  using: 'composite'
  steps:
    - name: Checkout Template dependencies
      uses: actions/checkout@v3
      with:
        fetch-depth: 0
        fetch-tags: true
        repository: "opencomputeproject/ocp-spec-tools"
        # The underlying tex and templates assume this exists under the "extra" folder.
        path: "extra"
    # let the container take ownership of the repo dir, in case the user wants to check in the results
    # workaround to https://github.com/actions/runner/issues/2033
    - run: chown -R $(id -u):$(id -g) $PWD
      shell: sh
    - run: >
        /usr/bin/build.sh
        --nogitversion
        --crossref=tcg
        --csl extra/ocp-pandoc-resources/ieee.csl
        --template extra/ocp-pandoc-resources/pdf/ocp.tex
        --template_html extra/ocp-pandoc-resources/html/ocp.html.template
        --html_stylesheet extra/ocp-pandoc-resources/html/style.css
        $( ${{ inputs.pdf }}  && echo --pdf=${{ inputs.output-basename }}.pdf )
        $( ${{ inputs.html }} && echo --html=${{ inputs.output-basename }}.html )
        ${{ inputs.input-md }}
      shell: sh
